// Feedback report 64 (2026-10-01): "convert from hip to gable end doesn't
// work properly, when i convert the gable to a hip, the two barges should
// turn into a gutter line, and there should be a ridge running between the
// two hips, it should look like a normal hip end". From the report's own
// lines (fixtures-report64.json): the roof carried an EARLIER structure (a
// ridge out to the left wall, hips at the right end) without the
// autoGenerated mark beside the new one (ridge, hips at the left), so both
// stood together and the stray ridge split the hip end's gutter into barges.
// Pinned: a conversion from that state clears every line the builders would
// draw on this outline and leaves a clean roof — either way round — while a
// line the office drew elsewhere stays; and a starter/finish barge that lost
// its mark in a reload still offers the conversion.
import { fileURLToPath as _f } from 'node:url';
import { dirname as _d, join as _j } from 'node:path';
import { readFileSync } from 'node:fs';
const _ROOT = _j(_d(_f(import.meta.url)), '..');
import { chromium } from 'playwright';
const DIR = _j(_ROOT, 'frontend');
const G = JSON.parse(readFileSync(_j(_ROOT, 'tests', 'fixtures-report64.json'), 'utf8'));
const results = [];
function check(n, ok, d){ results.push(!!ok); console.log((ok?'PASS':'FAIL')+'  '+n+(d?('  — '+d):'')); }
const b = await chromium.launch();
const pg = await (await b.newContext({ viewport:{ width:1500, height:1000 } })).newPage();
const errs = []; pg.on('pageerror', e => errs.push(e.message));
await pg.route('**/api.mapbox.com/**', r => r.abort());
await pg.route('**/flood-roofing-estimator-production.up.railway.app/**', r => r.fulfill({ status:200, contentType:'application/json', body:'[]' }));
await pg.addInitScript(() => { localStorage.setItem('fr_token','t'); localStorage.setItem('fr_setup_done','1'); localStorage.setItem('fr_settings','null'); localStorage.setItem('fr_shift_tip_off','1'); localStorage.setItem('fr_first_roof','never'); });
await pg.goto('file://' + DIR + '/app.html');
await pg.waitForTimeout(2500);

const load = (extra) => pg.evaluate(([g, extra]) => {
  gotoTab('roof'); clearAll(true);
  DRAW.scaleMetresPerPx = g.scaleMetresPerPx; DRAW.calPitch = g.calPitch;
  const sh = p => [p[0] - 1000, p[1] - 400];          // shifted into view
  DRAW.outline = g.outline.map(sh); DRAW.outlineDone = true;
  DRAW.lines = g.lines.map(l => Object.assign({}, l, { pts: l.pts.map(sh) }));
  if (extra) DRAW.lines.push({ type: 'valley', pts: [[60, 60], [100, 100]] });   // the office's own line, well off this roof
  DRAW.roofType = g.roofType; DRAW.rotation = 0; DRAW.roofBaseHoriz = true; DRAW.hipEnds = Object.assign({}, g.hipEnds);
  DRAW.roofs = [Object.assign(_newEmptyRoof('Main Roof'), { outline: DRAW.outline, lines: DRAW.lines })]; DRAW.activeRoofIdx = 0;
  _syncCurrentToRoof(); redrawAll();
}, [G, extra]);
const lines = () => pg.evaluate(() => DRAW.lines.map(l => ({ t: l.type, sub: l.subtype || '', he: l.hipEnd || '', p: l.pts.map(q => q.map(v => Math.round(v * 10) / 10)) })));
const count = (L, t) => L.filter(x => x.t === t).length;

// the state the report was sent in
await load(false);
let L = await lines();
check('the report’s roof: two ridges and four hips standing together (the fault, as sent)', count(L, 'ridge') === 2 && count(L, 'hip') === 4, JSON.stringify(L.map(x => x.t)));

// converting the hip end back to a gable, as in screenshot 1
let v = await pg.evaluate(() => { DRAW.selectedLine = DRAW.lines.findIndex(l => l.type === 'hip' && l.hipEnd === 'starter'); const o = _hipEndOf(DRAW.lines[DRAW.selectedLine]); _hipEndConvert(); return o; });
L = await lines();
const r = L.filter(x => x.t === 'ridge');
check('converting the hip end to a gable end leaves a clean gable: one ridge wall to wall, four barges, no hips',
  v && v.to === 'gable' && r.length === 1 && Math.min(...r[0].p.map(p => p[0])) === 219 && Math.max(...r[0].p.map(p => p[0])) === 350 &&
  count(L, 'hip') === 0 && count(L, 'barge') === 4 && count(L, 'gutter') === 2, JSON.stringify(L.map(x => x.t + x.sub)));

// and the gable end to a hip end, as the owner described it should look
v = await pg.evaluate(() => { DRAW.selectedLine = DRAW.lines.findIndex(l => l.type === 'barge' && l.subtype === 'starter'); const o = _hipEndOf(DRAW.lines[DRAW.selectedLine]); _hipEndConvert(); return o; });
L = await lines();
const r2 = L.filter(x => x.t === 'ridge'), hips = L.filter(x => x.t === 'hip'), endG = L.filter(x => x.t === 'gutter' && x.p.every(p => p[0] === 219));
check('converting it to a hip end: the two barges become ONE gutter line along that wall',
  v && v.to === 'hip' && endG.length === 1 && !L.some(x => x.t === 'barge' && x.p.every(p => p[0] === 219)), JSON.stringify(L.map(x => x.t + ':' + JSON.stringify(x.p))));
const rLo = r2.length ? Math.min(...r2[0].p.map(q => q[0])) : -1;
check('…and the ridge runs between the hips: one ridge, from where the hips meet to the far gable',
  r2.length === 1 && hips.length === 2 && hips.every(h => h.p.some(p => Math.abs(p[0] - rLo) < 0.2 && Math.abs(p[1] - r2[0].p[0][1]) < 0.2)) &&
  Math.max(...r2[0].p.map(p => p[0])) === 350, JSON.stringify({ r2, hips }));
check('…with the far end still a gable (its two barges)', count(L, 'barge') === 2 && L.filter(x => x.t === 'barge').every(x => x.p.every(p => p[0] === 350)));

// the same from the report's state, starting with a barge that lost its mark in a reload
await load(true);
v = await pg.evaluate(() => {
  DRAW.lines.forEach(l => { delete l.autoGenerated; });              // as a reload can leave them
  DRAW.selectedLine = DRAW.lines.findIndex(l => l.type === 'barge' && l.subtype === 'finish');
  const o = _hipEndOf(DRAW.lines[DRAW.selectedLine]); if (o) _hipEndConvert();
  return { o, valleys: DRAW.lines.filter(l => l.type === 'valley').length, ridges: DRAW.lines.filter(l => l.type === 'ridge').length,
           hips: DRAW.lines.filter(l => l.type === 'hip').length, barges: DRAW.lines.filter(l => l.type === 'barge').length };
});
check('a starter/finish barge with no autoGenerated mark (after a reload) still offers the conversion', v.o && v.o.to === 'hip', JSON.stringify(v));
check('…and converting it from the mixed state gives a clean hip at both ends — one ridge, four hips, no barges',
  v.ridges === 1 && v.hips === 4 && v.barges === 0, JSON.stringify(v));
check('…while a line the office drew elsewhere is left alone', v.valleys === 1, JSON.stringify(v));
check('nothing threw', errs.length === 0, errs.join(' | ').slice(0, 300));
await b.close();
const bad = results.filter(x => !x).length;
console.log('\n' + (results.length - bad) + '/' + results.length + ' passed');
process.exit(bad ? 1 : 0);
