// "It changes the width fine when I click gutter line or ridge line to
//  change, but not when I click a barge or sheet length — it never changed
//  the sheet and barge measure like it should."
//
// Two faults stacked. After a true-measure stretch, only AUTO-generated
// lines were rebuilt — lines restored from a saved job carry no autoGenerated
// flag, so their corners moved but the number printed on the pill stayed the
// old length. And the barge maths assumed the ridge re-centres (wall = typed
// ÷ fraction): on a saved job the ridge stays put, the far half swallows the
// whole stretch, and the tapped pill lands on some other number entirely —
// in plan metres at that, when a barge pill is a slope length.
//
// The segment solver stretches, re-measures and corrects until the TAPPED
// pill reads the typed number. This suite runs the exact roof from the
// report — gable, ridge held off-regen (saved-job lines), 15°, duplicate
// outline corners included.
import { fileURLToPath as _f } from 'node:url';
import { dirname as _d, join as _j } from 'node:path';
const _ROOT = _j(_d(_f(import.meta.url)), '..');
import { chromium } from 'playwright';
const DIR = _j(_ROOT, 'frontend');
const results = [];
function check(n, ok, d){ results.push(!!ok); console.log((ok?'PASS':'FAIL')+'  '+n+(d?('  — '+d):'')); }

const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1500,height:1000} });
const pg = await ctx.newPage();
const errs = []; pg.on('pageerror', e => errs.push(e.message));
pg.on('dialog', d => d.accept());
await pg.route('**/flood-roofing-estimator-production.up.railway.app/**',
  r => r.fulfill({status:200,contentType:'application/json',body:'[]'}));
await pg.addInitScript(() => { localStorage.setItem('fr_token','t');
  localStorage.setItem('fr_setup_done','1'); localStorage.setItem('fr_settings','null'); });
await pg.goto('file://'+DIR+'/app.html');
await pg.waitForTimeout(2600);

const load = () => pg.evaluate(() => {
  gotoTab('roof');
  DRAW.scaleMetresPerPx = 0.00787788238960114; DRAW.calPitch = 15;
  DRAW.outline = [[911,1044],[3133,1044],[3133,2039],[911,2039],[911,2039],[911,2039]];
  DRAW.outlineDone = true;
  DRAW.lines = [
    {type:'ridge',pts:[[911,1542],[3133,1542]],measM:17.5},
    {type:'gutter',pts:[[911,1044],[3133,1044]],measM:17.5},
    {type:'gutter',pts:[[3133,2039],[911,2039]],measM:17.5},
    {type:'barge',pts:[[3133,1044],[3133,1542]],measM:4.06,subtype:'finish'},
    {type:'barge',pts:[[3133,1542],[3133,2039]],measM:4.06,subtype:'finish'},
    {type:'barge',pts:[[911,2039],[911,1542]],measM:4.06,subtype:'starter'},
    {type:'barge',pts:[[911,1542],[911,1044]],measM:4.06,subtype:'starter'},
  ].map(l => Object.assign({label:'',lengthM:''}, l));
  DRAW.roofs = []; DRAW.sheetOverrides = {}; syncToRoofData();
  redrawAll();
});
await load();

// ── the report: tap the barge, type the real length ────────────────
let r = await pg.evaluate(() => {
  const tapped = DRAW.lines.find(l => l.type === 'barge' && l.pts[0][0] === 3133 && l.pts[0][1] === 1542);
  const em = _outlineEdgeForSegment(tapped.pts[0], tapped.pts[1]);
  const okFrac = em && em.frac < 0.98;
  const applied = _applySegmentTrueMeasure(em.idx, tapped, 6.00);
  return {
    okFrac, applied,
    lower: DRAW.lines.filter(l => l.type === 'barge' && l.pts.every(p => p[1] >= 1542)).map(l => l.measM),
    upper: DRAW.lines.filter(l => l.type === 'barge' && l.pts.every(p => p[1] <= 1542)).map(l => l.measM),
    gutters: DRAW.lines.filter(l => l.type === 'gutter').map(l => l.measM),
    wallPx: Math.abs(DRAW.outline[2][1] - DRAW.outline[1][1]),
  };
});
check('a barge half is recognised as part of its wall, not a full wall', r.okFrac);
check('typing 6.00 on the tapped barge makes THAT pill read 6.00',
  r.applied && r.lower.every(m => Math.abs(m - 6.00) < 0.011), r.lower.join(', '));
check('…the other half of the roof is not touched', r.upper.every(m => m === 4.06), r.upper.join(', '));
check('…and the gutters keep their length — only the depth stretched',
  r.gutters.every(m => m === 17.5), r.gutters.join(', '));
check('…because the wall genuinely grew', r.wallPx > 995 + 100, r.wallPx + 'px (was 995)');

// One undo takes the whole edit back — the solver iterates internally but
// must not cost the user six presses of Undo.
r = await pg.evaluate(() => {
  undoLast();
  return {
    wallPx: Math.abs(DRAW.outline[2][1] - DRAW.outline[1][1]),
    barges: DRAW.lines.filter(l => l.type === 'barge').map(l => l.measM),
  };
});
check('one Undo restores the drawing exactly',
  Math.abs(r.wallPx - 995) < 0.5 && r.barges.every(m => m === 4.06),
  r.wallPx + 'px, ' + r.barges.join(', '));

// ── gutters still edit the way they always did ─────────────────────
r = await pg.evaluate(() => {
  const g = DRAW.lines.find(l => l.type === 'gutter' && l.pts[0][1] === 1044);
  const em = _outlineEdgeForSegment(g.pts[0], g.pts[1]);
  _applyTrueEdgeMeasure(em.idx, 19.0);
  return {
    widthM: Math.abs(DRAW.outline[1][0] - DRAW.outline[0][0]) * DRAW.scaleMetresPerPx,
    gutter: DRAW.lines.filter(l => l.type === 'gutter' && Math.abs(l.pts[0][1] - l.pts[1][1]) < 1).map(l => l.measM),
  };
});
check('a full-wall gutter edit still stretches the width exactly',
  Math.abs(r.widthM - 19.0) < 0.02, r.widthM.toFixed(3) + 'm');
check('…and the gutter pills now SAY the new width — no stale labels',
  r.gutter.every(m => Math.abs(m - 19.0) < 0.011), r.gutter.join(', '));

// ── the sheet-length label drives the same solver ──────────────────
await load();
r = await pg.evaluate(() => {
  const hit = ((window._roofCanvasHits || {}).sheets || []).find(h => /4\.06/.test(h.label));
  if (!hit) return { noHit: true };
  _applySheetMeasureChange(hit, '5.5');
  return {
    barges: DRAW.lines.filter(l => l.type === 'barge').map(l => l.measM).sort(),
    overrides: Object.keys(DRAW.sheetOverrides || {}).length,
    wallPx: Math.abs(DRAW.outline[2][1] - DRAW.outline[1][1]),
  };
});
check('typing a sheet length stretches the roof so the run really is 5.50',
  !r.noHit && r.wallPx > 995 + 50, r.wallPx + 'px');
check('…the linked barge pill reads 5.50', r.barges && r.barges.some(m => Math.abs(m - 5.5) < 0.011),
  (r.barges || []).join(', '));
check('…as true geometry, not a label-only override', r.overrides === 0, r.overrides + ' overrides');

check('no page errors', errs.length === 0, errs.join(' | '));
const fails = results.filter(x => !x).length;
console.log('\n' + (results.length - fails) + '/' + results.length + ' passed');
await b.close();
process.exit(fails ? 1 : 0);
